version: "3.9"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:0.8.12
    container_name: open-webui
    volumes:
      - ${DATA_DIR}:/app/backend/data
    environment:
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
      - OPENAI_API_KEY=${VLLM_API_KEY:-dummy}
      - TZ=${TZ:-UTC}
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
    networks:
      traefik-net:
        aliases:
          - open-webui

networks:
  traefik-net:
    external: true
