http:
  routers:
    portainer:
      rule: "Host(`portainer.example.com`)"
      entryPoints:
        - websecure
      service: portainer-api
      tls: {}
    portainer-edge:
      rule: "Host(`edge.example.com`)"
      entryPoints:
        - websecure
      tls: {}
      service: portainer-edge

  services:
    portainer-api:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
    portainer-edge:
      loadBalancer:
        servers:
          - url: "http://portainer:8000"