services:
  feishin:
    image: ghcr.io/jeffvli/feishin:1.15.1
    container_name: feishin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      SERVER_NAME: ${SERVER_NAME}
      SERVER_LOCK: "true"
      SERVER_TYPE: navidrome
      SERVER_URL: ${SERVER_URL}
      REMOTE_URL: ${REMOTE_URL}
      LEGACY_AUTHENTICATION: "false"
      ANALYTICS_DISABLED: "true"
    networks:
      traefik-net:
        aliases:
          - feishin
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$

networks:
  traefik-net:
    external: true
