entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true
  insecure: false

# Optional: Uncomment the following lines to enable debug logging
#log:
#  level: "DEBUG"