tunnel: ${TUNNEL_NAME}
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
  - hostname: "domain1.example.com"
    service: https://traefik:443
    originRequest:
      noTLSVerify: true
  - hostname: "domain2.example.com"
    service: https://traefik:443
    originRequest:
      noTLSVerify: true
  - service: http_status:404