version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:2025.9.1
    container_name: cloudflared
    command: tunnel --no-autoupdate run ${TUNNEL_NAME}
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ./config.yaml:/etc/cloudflared/config.yaml
      - ${CERT_FILE}:/etc/cloudflared/cert.pem
      - ${CRED_FILE}:/etc/cloudflared/creds/credentials.json
    restart: unless-stopped
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true